### ISSUE TITLE
IPv6 address handling broken

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-mbed-os#36]
The commit entitled "fixes ipv6 addr handling" https://github.com/ARMmbed/mbed-client-mbed-os/commit/030e4f2ba3e706f9046cf2d762a75288a10036cd by @teetak01 actually breaks the previously working address handling. Reverting the commit allows registration again.

The commit uses only the first 4 bytes of the address. Might work if the other 12 bytes have been untouched or are correct by luck, only.

Is there an integration test that tests for IPv6 registration regressions?

**Comment by markus-becker-tridonic-com** [comment]
@mlnx

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-752

**Comment by teetak01** [comment]
@markus-becker-tridonic-com we did that change to fix another issue https://github.com/ARMmbed/mbed-client/issues/216, but appearantly the fix was not too good. We will review this issue again. We do have integration tests covering this.

Thank you for raising an issue on this.

**Comment by TeroJaasko** [comment]
@markus-becker-tridonic-com your analysis seems to be correct. Could you verify, if the PR https://github.com/ARMmbed/mbed-client-mbed-os/pull/38 fixes the issue you had?

**Comment by TeroJaasko** [comment]
@markus-becker-tridonic-com and/or @mlnx - any news if this works on your environment too? We are going to close the issue soon unless we get negative testing result. The issue can be re-opened later if needed.
