### ISSUE TITLE
Running tests on the embedded target

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-mbed-os#39]
Do we support cross-compilation of unit tests in order to run them on the embedded target? I did the following on my Linux development machine:

> cd mbed-client-mbed-os
> yt target frdm-k64f-gcc
> make test

This results in the tests being built using the native Linux compiler and run on the x86 machine. What would be the procedure to cross-compile them (if the support is available)?

Thanks for your help.

**Comment by yogpan01** [comment]
Hi,
Unit tests are only for verifying unit level sanity of the code, which means all the other external components are stubbed while testing the particular class function. We are using CppUTest framework for unit testing hence the support is only limited for Linux builds which is sufficient for unit testing the component.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-829

**Comment by vanti** [comment]
Thanks for the explanation. It was unclear to me given this is the mbed-os-specific part of the mbed client.
